# Generated by Django 5.2.17 on 2026-09-18 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworker',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='worker',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
