# Generated by Django 6.0.6 on 2026-08-06 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('building_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Infrastructure', 'Infrastructure'), ('Mixed-Use', 'Mixed-Use')], default='Commercial', max_length=50)),
                ('blocks', models.PositiveIntegerField(default=1)),
                ('floors', models.PositiveIntegerField(default=1)),
                ('area_sqft', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('current_progress', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNING', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
