import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ClipboardList } from 'lucide-react';

const DailyLogDetailsModal = ({ isOpen, onClose, logItem }) => {
  if (!isOpen || !logItem) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm overflow-y-auto">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="bg-white rounded-3xl shadow-2xl border border-gray-100 w-full max-w-xl overflow-hidden text-[#003135] my-8"
        >
          {/* Header */}
          <div className="bg-[#003135] text-white px-6 py-5 flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 rounded-xl bg-[#0FA4AF]/20 border border-[#0FA4AF]/40 flex items-center justify-center text-[#0FA4AF]">
                <ClipboardList className="w-5 h-5" />
              </div>
              <div>
                <div className="flex items-center space-x-2">
                  <span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-[#0FA4AF] text-white">
                    {logItem.progress_id}
                  </span>
                  <h3 className="text-base font-extrabold tracking-tight">
                    Day {logItem.day_number} - {logItem.project_detail?.project_name}
                  </h3>
                </div>
                <p className="text-xs text-[#AFDDE5] mt-0.5">
                  AI Dataset Record generated by {logItem.created_by_detail ? logItem.created_by_detail.full_name : 'Site Engineer'}
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-1.5 rounded-full hover:bg-white/10 text-gray-300 hover:text-white transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="p-6 space-y-6 max-h-[80vh] overflow-y-auto">
            
            {/* Quick Metrics Bar */}
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 bg-gray-50 p-4 rounded-2xl border border-gray-200">
              <div>
                <p className="text-[10px] uppercase font-bold text-gray-500">Day Number</p>
                <p className="text-sm font-extrabold text-[#003135]">Day {logItem.day_number}</p>
              </div>

              <div>
                <p className="text-[10px] uppercase font-bold text-gray-500">Construction Stage</p>
                <p className="text-xs font-extrabold text-[#003135] truncate">{logItem.construction_stage}</p>
              </div>

              <div>
                <p className="text-[10px] uppercase font-bold text-gray-500">Workers (Current/Expected)</p>
                <p className="text-xs font-extrabold text-blue-600">{logItem.current_workers} / {logItem.expected_workers}</p>
              </div>
            </div>

            {/* AI Dataset Fields Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="p-4 rounded-2xl bg-slate-50 border border-gray-200 space-y-1">
                <p className="text-[10px] font-bold uppercase text-gray-500">Building Type & Specs</p>
                <h4 className="text-sm font-extrabold text-[#003135]">{logItem.building_type}</h4>
                <p className="text-[10px] text-gray-500">{logItem.blocks} Blocks | {logItem.floors} Floors | {Number(logItem.area_sqft).toLocaleString()} sqft</p>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-gray-200 space-y-1">
                <p className="text-[10px] font-bold uppercase text-gray-500">Total Budget & Used</p>
                <h4 className="text-sm font-extrabold text-amber-600">₹{Number(logItem.budget_used).toLocaleString()}</h4>
                <p className="text-[10px] text-gray-500">of ₹{Number(logItem.total_budget).toLocaleString()}</p>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-gray-200 space-y-1">
                <p className="text-[10px] font-bold uppercase text-gray-500">Attendance Percentage</p>
                <h4 className="text-xl font-extrabold text-[#0FA4AF]">{logItem.attendance_percentage}%</h4>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-gray-200 space-y-1">
                <p className="text-[10px] font-bold uppercase text-gray-500">Overall Progress Percentage</p>
                <h4 className="text-xl font-extrabold text-emerald-600">{logItem.progress_percentage}%</h4>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-gray-200 space-y-1 sm:col-span-2">
                <p className="text-[10px] font-bold uppercase text-gray-500">Rainfall & Work Impact</p>
                <div className="flex items-center justify-between">
                  <h4 className="text-lg font-extrabold text-blue-500">{logItem.rainfall_mm} mm</h4>
                  <span className={`text-xs font-bold px-2.5 py-0.5 rounded-full ${
                    logItem.rain_affected_work ? 'bg-red-100 text-red-700' : 'bg-emerald-100 text-emerald-700'
                  }`}>
                    Rain Affected Work: {logItem.rain_affected_work ? 'YES' : 'NO'}
                  </span>
                </div>
              </div>
            </div>

          </div>

          <div className="p-4 bg-gray-50 border-t border-gray-100 flex items-center justify-end">
            <button
              onClick={onClose}
              className="px-5 py-2 bg-[#003135] text-white text-xs font-bold rounded-xl hover:bg-[#024950] transition-colors cursor-pointer"
            >
              Close View
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};

export default DailyLogDetailsModal;
