# Generated by Django 5.2.17 on 2026-09-23 10:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='SiteSense', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('working_days_per_week', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('standard_shift_hours', models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(24.0)])),
                ('budget_alert_threshold', models.FloatField(default=85.0, help_text='Flag a project once this share of its budget is consumed.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('attendance_alert_threshold', models.FloatField(default=70.0, help_text='Flag a project when attendance falls below this percentage.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ai_high_risk_threshold', models.FloatField(default=60.0, help_text='Delay probability at or above this counts as High risk.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_organization_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Setting',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light')], default='DARK', max_length=10)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20)),
                ('default_landing_page', models.CharField(choices=[('projects', 'Projects'), ('workers', 'Workers'), ('attendance', 'Attendance'), ('tasks', 'Tasks'), ('materials', 'Materials & Expenses'), ('dailylogs', 'Daily Logs'), ('ai', 'AI Engine'), ('reports', 'Reports')], default='projects', max_length=20)),
                ('items_per_page', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('compact_tables', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('notify_task_assigned', models.BooleanField(default=True)),
                ('notify_task_status_change', models.BooleanField(default=True)),
                ('notify_attendance_summary', models.BooleanField(default=False)),
                ('notify_material_purchase', models.BooleanField(default=True)),
                ('notify_budget_overspend', models.BooleanField(default=True)),
                ('notify_ai_risk_alert', models.BooleanField(default=True)),
                ('notify_daily_log_reminder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'ordering': ['user_id'],
            },
        ),
    ]
