# Generated by Django 5.2.17 on 2026-09-18 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpurchase',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
