# Generated by Django 6.0.6 on 2026-08-06 12:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('construction_stage', models.CharField(choices=[('Excavation & Substructure', 'Excavation & Substructure'), ('Foundation & Slab Pouring', 'Foundation & Slab Pouring'), ('Structural Steel & Superstructure', 'Structural Steel & Superstructure'), ('Masonry & External Walls', 'Masonry & External Walls'), ('MEP Rough-In', 'MEP Rough-In'), ('Interior Finishing', 'Interior Finishing'), ('Façade & Cladding', 'Façade & Cladding'), ('Landscaping & Handover', 'Landscaping & Handover')], default='Structural Steel & Superstructure', max_length=100)),
                ('progress_notes', models.TextField(blank=True, default='')),
                ('rainfall_mm', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('temperature_celsius', models.DecimalField(decimal_places=1, default=25.0, max_digits=5)),
                ('weather_condition', models.CharField(choices=[('Sunny', 'Sunny'), ('Partly Cloudy', 'Partly Cloudy'), ('Overcast', 'Overcast'), ('Light Rain', 'Light Rain'), ('Heavy Rain / Storm', 'Heavy Rain / Storm'), ('High Winds', 'High Winds')], default='Sunny', max_length=50)),
                ('machine_downtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('machine_downtime_reason', models.TextField(blank=True, default='')),
                ('safety_incidents_count', models.IntegerField(default=0)),
                ('safety_incident_details', models.TextField(blank=True, default='')),
                ('workers_present_count', models.IntegerField(default=0)),
                ('workers_absent_count', models.IntegerField(default=0)),
                ('work_completed_today', models.TextField(blank=True, default='')),
                ('problems_encountered', models.TextField(blank=True, default='')),
                ('material_shortage_notes', models.TextField(blank=True, default='')),
                ('engineer_remarks', models.TextField(blank=True, default='')),
                ('site_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
