# Generated by Django 6.0.6 on 2026-08-06 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailylogs', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('day_number', models.PositiveIntegerField()),
                ('current_workers', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rainfall_mm', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('rain_affected_work', models.BooleanField(default=False)),
                ('construction_stage', models.CharField(choices=[('Excavation & Substructure', 'Excavation & Substructure'), ('Foundation & Slab Pouring', 'Foundation & Slab Pouring'), ('Structural Steel & Superstructure', 'Structural Steel & Superstructure'), ('Masonry & External Walls', 'Masonry & External Walls'), ('MEP Rough-In', 'MEP Rough-In'), ('Interior Finishing', 'Interior Finishing'), ('Façade & Cladding', 'Façade & Cladding'), ('Landscaping & Handover', 'Landscaping & Handover')], default='Structural Steel & Superstructure', max_length=100)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_progress', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='projects.project')),
            ],
            options={
                'ordering': ['-day_number', '-created_at'],
                'unique_together': {('project', 'day_number')},
            },
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
    ]
