# Generated by Django 6.0.6 on 2026-08-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailylogs', '0002_projectdailyprogress_delete_dailylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdailyprogress',
            name='area_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='projectdailyprogress',
            name='blocks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectdailyprogress',
            name='building_type',
            field=models.CharField(default='Residential', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdailyprogress',
            name='expected_workers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdailyprogress',
            name='floors',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectdailyprogress',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='projectdailyprogress',
            name='budget_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
